name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies (if present)
        run: |
          if [ -f package-lock.json ]; then
            npm ci --ignore-scripts --no-audit --no-fund
          else
            echo "No root package-lock.json; skipping install."
          fi
      - name: Lint
        run: |
          if [ -f package.json ]; then
            npm run -s lint --if-present
          else
            echo "No package.json; skipping lint."
          fi

  test:
    name: test
    runs-on: ubuntu-latest
    needs: [lint]
    timeout-minutes: 10
    env:
      CI: 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies (if present)
        run: |
          if [ -f package-lock.json ]; then
            npm ci --ignore-scripts --no-audit --no-fund
          else
            echo "No root package-lock.json; skipping install."
          fi
      - name: Test
        run: |
          if [ -f package.json ]; then
            npm test --if-present
          else
            echo "No package.json; skipping test."
          fi

  build:
    name: build
    runs-on: ubuntu-latest
    needs: [test]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies (if present)
        run: |
          if [ -f package-lock.json ]; then
            npm ci --ignore-scripts --no-audit --no-fund
          else
            echo "No root package-lock.json; skipping install."
          fi
      - name: Build
        run: |
          if [ -f package.json ]; then
            npm run -s build --if-present
          else
            echo "No package.json; skipping build."
          fi
