name: Dependency Review (PR)
on: [ pull_request ]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          # Conservative to start; we tighten in S20 if needed.
          fail-on-severity: critical
          # To post a summary comment, also grant 'pull-requests: write' and set:
          # comment-summary-in-pr: true
